const assert = require('node:assert/strict');
const path = require('node:path');

module.exports = async ({ host, browser, baseUrl, video, wait }) => {
 const panel = host.locator('.appearance-panel');
 const shell = host.locator('.room-shell');
 const settings = page => page.evaluate(() => JSON.parse(localStorage.getItem('watchly-appearance-settings')));
 const open = async () => {
  await host.mouse.move(650, 400);
  if (!await panel.count()) await host.getByRole('button', { name: 'Room settings', exact: true }).click();
 };
 const close = async () => {
  await host.getByRole('button', { name: 'Room settings', exact: true }).click();
  await panel.waitFor({ state: 'hidden' });
 };
 const choice = name => panel.getByRole('button', { name: new RegExp('^' + name + '(?: |$)') }).click();
 const toggle = name => panel.getByRole('switch', { name, exact: true }).click();
 const css = (selector, property) => host.locator(selector).first().evaluate((el, property) => getComputedStyle(el)[property], property);
 const watchControls = host.getByRole('button', { name: 'Watch controls', exact: true });
 if (await watchControls.getAttribute('aria-expanded') === 'true') await watchControls.click();
 await video(host).evaluate(el => { el.currentTime = 1; });
 await host.evaluate(() => { window.appearanceVideo = document.querySelector('.room-player-surface video'); });
 const before = await video(host).evaluate(el => ({ src: el.currentSrc, time: el.currentTime }));
 await open();
 assert.equal(await panel.getByText('Cinema Luxe', { exact: true }).count(), 0);
 assert.equal(await panel.getByRole('heading').count(), 6);
 const bounds = await panel.boundingBox();
 assert.ok(bounds.width >= 390 && bounds.width <= 420);
 assert.ok(bounds.y >= 0 && bounds.y + bounds.height <= 720);
 await choice('Classic');
 assert.equal(await shell.getAttribute('data-room-appearance'), 'classic');
 assert.equal(await panel.getByRole('heading', { name: 'Cinema preset', exact: true }).count(), 0);
 assert.equal(await panel.getByRole('switch').count(), 0);
 assert.equal(await host.locator('.cinema-luxe-scene').count(), 0);
 await choice('Light Glass');
 assert.equal(await shell.getAttribute('data-theme'), 'glass-light');
 await choice('Cinematic');
 assert.equal(await shell.getAttribute('data-room-appearance'), 'cinematic');
 assert.equal(await panel.getByRole('heading', { name: 'Ambience', exact: true }).count(), 1);
 const lightHeader = await css('.room-header', 'backgroundColor');
 await choice('Dark Glass');
 assert.notEqual(await css('.room-header', 'backgroundColor'), lightHeader, 'UI theme must change chrome independently');
 assert.equal((await settings(host)).cinemaPreset, 'luxe');
 await choice('Minimal');
 let saved = await settings(host);
 assert.equal(saved.roomBrightness, 15);
 for (const key of ['sofa', 'aisleLights', 'wallDetails']) assert.equal(saved[key], false);
 assert.equal(await host.locator('.luxe-sofa').isVisible(), false);
 assert.equal(await host.locator('.luxe-aisle').first().isVisible(), false);
 assert.equal(await host.locator('.luxe-wall-left').evaluate(el => getComputedStyle(el, '::before').display), 'none');
 assert.equal(await shell.getAttribute('data-cinema-ambient'), 'neutral', 'Minimal keeps neutral ambient instead of sampling movie colours');
 await toggle('Sofa');
 await choice('Light Glass');
 assert.equal((await settings(host)).sofa, true, 'changing UI theme must preserve manual cinema overrides');
 assert.equal((await settings(host)).roomBrightness, 15);
 await choice('Luxe');
 saved = await settings(host);
 assert.equal(saved.roomBrightness, 35);
 for (const key of ['ambientLighting', 'sofa', 'aisleLights', 'wallDetails', 'autoHideControls', 'dimWhilePlaying', 'screenExpansion']) assert.equal(saved[key], true);
 assert.equal(saved.hideDelay, 3);
 assert.equal(saved.reduceMotion, false);
 await choice('Dark Glass');
 await wait(async () => await shell.getAttribute('data-cinema-ambient') === 'sampled', 'Luxe should restore existing safe ambient sampling');
 await host.evaluate(() => {
  window.appearanceReads = 0;
  window.appearanceReadPixels = CanvasRenderingContext2D.prototype.getImageData;
  CanvasRenderingContext2D.prototype.getImageData = function (...args) { window.appearanceReads++; return window.appearanceReadPixels.apply(this, args); };
 });
 await toggle('Ambient screen lighting');
 assert.equal(await css('.luxe-ambient', 'display'), 'none');
 assert.equal(await shell.getAttribute('data-cinema-ambient'), 'disabled');
 await host.evaluate(() => { window.appearanceReads = 0; });
 await host.waitForTimeout(1100);
 assert.equal(await host.evaluate(() => window.appearanceReads), 0, 'disabled ambient lighting must stop pixel sampling');
 assert.equal((await video(host).evaluate(el => el.paused)), false);
 await toggle('Ambient screen lighting');
 await host.waitForTimeout(1100);
 const readCount = await host.evaluate(() => window.appearanceReads);
 assert.ok(readCount >= 2 && readCount <= 4, 'one sampling loop should resume without duplicate intervals');
 await host.evaluate(() => { CanvasRenderingContext2D.prototype.getImageData = window.appearanceReadPixels; });
 const geometry = await host.locator('.room-player-surface').boundingBox();
 const textColor = await css('.appearance-row', 'color');
 const brightness = panel.getByRole('slider', { name: /Room brightness/ });
 await brightness.focus(); await brightness.press('Home');
 assert.equal((await settings(host)).roomBrightness, 0);
 const lowest = await css('.luxe-floor', 'filter');
 await brightness.press('End');
 assert.equal((await settings(host)).roomBrightness, 100);
 assert.notEqual(await css('.luxe-floor', 'filter'), lowest);
 await brightness.press('Home');
 await brightness.press('PageUp'); await brightness.press('PageUp');
 const lower = await css('.luxe-floor', 'filter');
 await brightness.press('PageUp'); await brightness.press('PageUp'); await brightness.press('PageUp');
 assert.notEqual(await css('.luxe-floor', 'filter'), lower);
 assert.deepEqual(await host.locator('.room-player-surface').boundingBox(), geometry);
 assert.equal(await css('.room-player-surface', 'filter'), 'none');
 assert.equal(await css('.appearance-row', 'color'), textColor);
 for (const [label, selector] of [['Sofa', '.luxe-sofa'], ['Aisle lights', '.luxe-aisle']]) {
  await toggle(label); assert.equal(await css(selector, 'display'), 'none');
  await toggle(label); assert.notEqual(await css(selector, 'display'), 'none');
 }
 const detailedWall = await css('.luxe-wall-left', 'backgroundImage');
 const detailedCeiling = await css('.luxe-ceiling', 'backgroundImage');
 await toggle('Wall details');
 assert.notEqual(await css('.luxe-wall-left', 'backgroundImage'), detailedWall);
 assert.notEqual(await css('.luxe-ceiling', 'backgroundImage'), detailedCeiling);
 assert.equal(await host.locator('.luxe-wall-left').isVisible(), true);
 assert.equal(await host.locator('.luxe-ceiling').isVisible(), true);
 await toggle('Wall details');
 await toggle('Dim room while playing'); await host.waitForTimeout(850);
 assert.equal(await css('.luxe-wall-left', 'opacity'), '1');
 await toggle('Dim room while playing'); await host.waitForTimeout(850);
 assert.equal(await css('.luxe-wall-left', 'opacity'), '0.6');
 await toggle('Screen expansion'); await host.waitForTimeout(850);
 const unexpanded = await host.locator('.room-player-surface').boundingBox();
 assert.ok(Math.abs(geometry.width / unexpanded.width - 1.04) < 0.001);
 await toggle('Screen expansion'); await host.waitForTimeout(850);
 await toggle('Reduce motion');
 assert.equal(await css('.room-player-surface', 'transitionDuration'), '0s');
 assert.ok(Math.abs((await host.locator('.room-player-surface').boundingBox()).width - unexpanded.width) < 1);
 await toggle('Reduce motion');
 await host.emulateMedia({ reducedMotion: 'reduce' }); await host.waitForTimeout(100);
 assert.ok(Math.abs((await host.locator('.room-player-surface').boundingBox()).width - unexpanded.width) < 1, 'OS reduce motion must disable expansion even when user preference is off');
 await host.emulateMedia({ reducedMotion: 'no-preference' });
 await toggle('Auto-hide controls');
 assert.equal(await panel.getByLabel('Hide controls after').isDisabled(), true);
 await close(); await host.evaluate(() => document.activeElement.blur()); await host.mouse.move(640, 650);
 await host.waitForTimeout(3400);
 assert.equal(await shell.getAttribute('data-cinema-controls-hidden'), null);
 await open(); await toggle('Auto-hide controls');
 for (const delay of ['2', '3', '5']) {
  await panel.getByLabel('Hide controls after').selectOption(delay);
  await close(); await host.evaluate(() => document.activeElement.blur()); await host.mouse.move(640, 650);
  await host.waitForTimeout(Number(delay) * 1000 - 200);
  assert.equal(await shell.getAttribute('data-cinema-controls-hidden'), null, 'controls must stay visible before the selected delay');
  await wait(async () => await shell.getAttribute('data-cinema-controls-hidden') === 'true', 'controls must hide at the selected delay');
  await open();
 }
 await host.evaluate(() => document.activeElement.blur()); await host.mouse.move(640, 650); await host.waitForTimeout(5300);
 assert.equal(await shell.getAttribute('data-cinema-controls-hidden'), null, 'open Appearance panel must prevent hiding');
 await panel.getByLabel('Hide controls after').selectOption('never');
 await close(); await host.evaluate(() => document.activeElement.blur()); await host.mouse.move(640, 650); await host.waitForTimeout(5300);
 assert.equal(await shell.getAttribute('data-cinema-controls-hidden'), null, 'Never must clear all hide timers');
 await open();
 const custom = await settings(host);
 await panel.screenshot({ path: path.resolve(__dirname, '../../appearance-panel-desktop-visual-verification.png') });
 await host.keyboard.press('Escape'); await panel.waitFor({ state: 'hidden' });
 assert.equal(await host.getByRole('button', { name: 'Room settings', exact: true }).evaluate(el => el === document.activeElement), true);
 await open(); await host.mouse.click(600, 650); await panel.waitFor({ state: 'hidden' });
 const idle = await browser.newPage({ viewport: { width: 390, height: 844 } });
 const errors = []; idle.on('pageerror', error => errors.push(error.message));
 await idle.goto(baseUrl);
 await idle.evaluate(saved => localStorage.setItem('watchly-appearance-settings', JSON.stringify(saved)), custom);
 await idle.reload();
 await idle.getByRole('button', { name: 'Create room', exact: true }).first().click();
 await idle.getByPlaceholder('Your nickname').fill('Appearance persistence'); await idle.locator('.room-launcher-submit').click();
 await idle.waitForURL('**/room/**'); await idle.getByRole('heading', { name: 'No video playing' }).waitFor();
 await idle.reload(); await idle.getByRole('heading', { name: 'No video playing' }).waitFor();
 assert.deepEqual(await settings(idle), custom, 'all customized settings must survive reload');
 await idle.getByRole('button', { name: 'Room settings', exact: true }).click();
 const mobilePanel = idle.locator('.appearance-panel');
 for (const viewport of [{ width: 390, height: 844 }, { width: 844, height: 390 }, { width: 1024, height: 768 }]) {
  await idle.setViewportSize(viewport); await idle.waitForTimeout(200);
  const box = await mobilePanel.boundingBox();
  assert.ok(box.x >= 0 && box.y >= 0 && box.x + box.width <= viewport.width && box.y + box.height <= viewport.height, 'panel must fit compact viewports');
  assert.equal(await idle.locator('.room-shell').getAttribute('data-room-appearance'), 'classic');
  const scroll = await mobilePanel.locator('.appearance-panel-body').evaluate(el => { el.scrollTop = el.scrollHeight; return { top: el.scrollTop, available: el.clientHeight }; });
  assert.ok(scroll.top > 0 && scroll.available > 0, 'settings must scroll internally');
  assert.ok(await mobilePanel.getByRole('button', { name: 'Reset appearance' }).isVisible());
 }
 await idle.setViewportSize({ width: 390, height: 844 });
 await mobilePanel.locator('.appearance-panel-body').evaluate(el => { el.scrollTop = 0; });
 await mobilePanel.screenshot({ path: path.resolve(__dirname, '../../appearance-panel-mobile-visual-verification.png') });
 await idle.keyboard.press('Escape');
 await idle.evaluate(() => { localStorage.removeItem('watchly-appearance-settings'); localStorage.setItem('watchly-theme', 'cinema-luxe'); localStorage.setItem('watchly-room-appearance', 'classic'); });
 await idle.reload(); await idle.getByRole('heading', { name: 'No video playing' }).waitFor();
 assert.equal((await settings(idle)).roomStyle, 'cinematic');
 assert.equal((await settings(idle)).uiTheme, 'glass-dark');
 assert.equal((await settings(idle)).cinemaPreset, 'luxe');
 assert.deepEqual(errors,[]); await idle.close();
 await open(); await panel.getByRole('button', { name: 'Reset appearance' }).click(); await close();
 saved = await settings(host); assert.equal(saved.roomBrightness, 35); assert.equal(saved.hideDelay, 3); assert.equal(saved.uiTheme, 'glass-dark');
 assert.equal(await host.evaluate(() => window.appearanceVideo === document.querySelector('.room-player-surface video')), true);
 assert.equal(await video(host).evaluate(el => el.currentSrc), before.src);
 assert.equal(await video(host).evaluate(el => el.paused), false);
 assert.ok(await video(host).evaluate(el => el.currentTime) > before.time, 'appearance controls must not interrupt video time');
 await watchControls.click();
 console.log('PASS appearance: independent styles/themes, presets, all ambience and playback options, timed hiding, reduced motion, persistence/migration, reset, overlay closing and compact layouts');
};
