const assert = require('node:assert/strict');
const path = require('node:path');

module.exports = async ({ a, b, floating, open, wait, decode, audio, evidence, artifacts }) => {
    const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
    const reveal = () => floating.hover({ position: { x: 10, y: 10 } });
    const click = async name => { await reveal(); await floating.getByRole('button', { name, exact: true }).click(); };
    const visible = async value => wait(async () => await floating.getAttribute('data-controls-visible') === String(value), `controls did not become ${value}`, 6000);
    const cameraA = b.locator('.call-camera-tile').filter({ hasText: 'Camera A' });
    await a.evaluate(() => { window.floatingBaseline = { room: window.testCallRoom, sid: window.testCallRoom.localParticipant.sid, camera: window.testCallRoom.localParticipant.getTrackPublication('camera').track.mediaStreamTrack, tokens: window.callTokenRequests }; });
    const initial = await floating.boundingBox();
    const resize = async (edge, dx, dy) => {
        const handle = await floating.locator(`.floating-call-resize[data-edge="${edge}"]`).boundingBox();
        const x = handle.x + handle.width / 2, y = handle.y + handle.height / 2;
        await a.mouse.move(x, y); await a.mouse.down(); await a.mouse.move(x + dx, y + dy, { steps: 6 }); await a.mouse.up();
    };
    await resize('top-left', -90, -60);
    await wait(async () => (await floating.boundingBox()).width > initial.width + 85, 'top-left resize did not grow camera');
    const grown = await floating.boundingBox(); assert.ok(Math.abs(grown.x + grown.width - initial.x - initial.width) < 2); assert.ok(grown.height > initial.height + 55);
    await resize('right', -40, 0); await wait(async () => (await floating.boundingBox()).width < grown.width - 35, 'edge resize failed');
    assert.equal((await floating.boundingBox()).height, grown.height);
    const beforeKeys = await floating.boundingBox();
    await floating.getByRole('button', { name: 'Resize video call', exact: true }).focus(); await a.keyboard.press('ArrowUp');
    await wait(async () => (await floating.boundingBox()).height === beforeKeys.height - 16, 'keyboard resize failed');
    await a.evaluate(() => document.activeElement.blur());
    await wait(async () => await floating.locator('.call-camera-tile').count() === 1, 'remote-only float missing');
    assert.equal(await floating.locator('.call-camera-tile').filter({ hasText: 'Camera A' }).count(), 0);
    assert.equal(await floating.locator('header,.video-call-status,.video-call-actions,.call-device-settings').count(), 0);
    await wait(async () => { try { return (await decode(a, 'Camera B')).pixel[2] > 170; } catch { return false; } }, 'floating remote video not decoded');
    assert.equal(await cameraA.getAttribute('data-camera-on'), 'true');
    const frame = await floating.boundingBox(), video = await floating.locator('video').boundingBox();
    assert.ok(Math.abs(frame.width - video.width) < 5 && Math.abs(frame.height - video.height) < 5, 'video does not fill frame');
    await reveal(); await visible(true); await pause(2300); await visible(false); // Idle while still over video.
    await a.screenshot({ path: path.join(artifacts, 'floating-video-only.png') });
    await reveal(); await floating.getByRole('button', { name: 'Restore video panel', exact: true }).hover(); await pause(2300); await visible(true);
    await a.screenshot({ path: path.join(artifacts, 'floating-video-controls.png') });
    await a.mouse.move(1, 1); await visible(false);
    await floating.getByRole('button', { name: 'Unmute microphone', exact: true }).focus(); await a.keyboard.press('Tab'); await visible(true); await pause(2300); await visible(true);
    await a.evaluate(() => document.activeElement.blur()); await visible(false);
    await click('Unmute microphone'); await wait(async () => (await audio(b)).rms > .01, 'floating unmute failed');
    await click('Mute microphone'); await wait(async () => (await audio(b)).rms < .003, 'floating mute failed');
    await click('Turn camera off'); await cameraA.locator('.call-camera-fallback').waitFor();
    assert.equal(await floating.locator('.call-camera-tile').count(), 1); // Remote stays visible with own camera off.
    await click('Turn camera on'); await wait(async () => { try { return (await decode(b, 'Camera A')).pixel[0] > 170; } catch { return false; } }, 'floating camera enable failed');
    const afterControls = await floating.boundingBox(); assert.equal(afterControls.x, frame.x); assert.equal(afterControls.y, frame.y);
    await click('Turn camera off'); await a.evaluate(() => window.denyCamera = true); await click('Turn camera on');
    await floating.getByRole('alert').filter({ hasText: /Camera access blocked/ }).waitFor();
    await a.evaluate(() => window.denyCamera = false); await click('Turn camera on'); await cameraA.locator('video').waitFor();
    await open(b, 'Video'); await b.getByRole('button', { name: 'Turn camera off', exact: true }).click();
    await floating.locator('.call-camera-fallback').waitFor(); assert.match(await floating.locator('.call-camera-fallback').innerText(), /Camera B/);
    await b.getByRole('button', { name: 'Turn camera on', exact: true }).click(); await floating.locator('video').waitFor();
    await b.getByRole('button', { name: 'Leave call', exact: true }).click(); await floating.getByText('Waiting for others…', { exact: true }).waitFor();
    assert.equal(await floating.locator('.call-camera-tile').count(), 0);
    assert.equal(await a.evaluate(() => window.testCallRoom.localParticipant.isCameraEnabled), true);
    await b.getByRole('button', { name: 'Join video', exact: true }).click(); await b.locator('.video-call-content[data-camera-on="true"]').waitFor();
    await b.getByRole('button', { name: 'Unmute microphone', exact: true }).click(); await floating.locator('video').waitFor();
    await a.setViewportSize({ width: 390, height: 844 });
    const beforeTouch = await floating.boundingBox(), cdp = await a.context().newCDPSession(a);
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: beforeTouch.x + 13, y: beforeTouch.y + 13 }] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: beforeTouch.x + 43, y: beforeTouch.y + 43 }] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await cdp.detach();
    await wait(async () => (await floating.boundingBox()).width < beforeTouch.width - 25, 'touch corner resize failed');
    await a.mouse.move(1, 1); await visible(false);
    const tap = async () => { const box = await floating.boundingBox(); await a.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 2); };
    await tap(); await visible(true); await tap(); await visible(false); await tap(); await visible(true); await pause(3300); await visible(false);
    await a.screenshot({ path: path.join(artifacts, 'floating-video-touch.png') });
    await a.setViewportSize({ width: 1366, height: 768 });
    assert.equal(await a.evaluate(() => window.testCallRoom === window.floatingBaseline.room && window.testCallRoom.localParticipant.sid === window.floatingBaseline.sid && window.callTokenRequests === window.floatingBaseline.tokens), true);
    evidence.checks.push('Floating video fills frame with remote only; own camera keeps transmitting; zero-peer waiting, remote camera-off avatar, real mic/camera toggles, desktop idle/hover hold/leave, touch toggle/3s hide; corner/edge/keyboard/touch resizing pass');
};
